---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 刘思龙.
--- DateTime: 2022/10/16 10:40
---

if(redis.call('get',KEYS[1])==ARGV[1]) then
    --释放锁 del key
    return redis.call('del',KEYS[1])
end
return 0